#ifndef CONFIG_H
#define CONFIG_H

#define NUM_CELLS 6
#define ADC_MAX 1023.0
#define REF_VOLTAGE 5.0
#define VOLTAGE_DIVIDER_RATIO 2.0
#define MIN_CELL_VOLTAGE 3.0
#define MAX_CELL_VOLTAGE 4.2
#define BALANCE_THRESHOLD 0.05

#endif
